MODEL:
  BACKBONE: 'resnet50'
  PRETRAIN_PATH: ''
  ID_LOSS_TYPE: 'softmax'
  METRIC_LOSS_TYPE: 'none'
  SMOOTH_LABEL: False

INPUT:
  AUTOAUG_PROB: 0.0
  AUGMIX_PROB: 0.0
  CJ_PROB: 0.0
  RE_PROB: 0.5

DATASETS:
  ROOT_DIR: '/home/xiangyuzhu/data/ReID'
  TRAIN: ('market1501',)
  TEST: ('market1501',)

DATALOADER:
  SAMPLER: 'random_identity'
  NUM_INSTANCE: 4

SOLVER:
  FP16: True
  BASE_LR: 3.5e-4
  BATCH_SIZE: 64
  MAX_EPOCHS: 30
  EVAL_PERIOD: 10
  FREEZE_EPOCHS: 1